package entity;

public class Admininfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admininfo.id
     *
     * @mbggenerated Thu Mar 31 16:04:31 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admininfo.name
     *
     * @mbggenerated Thu Mar 31 16:04:31 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admininfo.password
     *
     * @mbggenerated Thu Mar 31 16:04:31 CST 2016
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admininfo.id
     *
     * @return the value of admininfo.id
     *
     * @mbggenerated Thu Mar 31 16:04:31 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admininfo.id
     *
     * @param id the value for admininfo.id
     *
     * @mbggenerated Thu Mar 31 16:04:31 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admininfo.name
     *
     * @return the value of admininfo.name
     *
     * @mbggenerated Thu Mar 31 16:04:31 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admininfo.name
     *
     * @param name the value for admininfo.name
     *
     * @mbggenerated Thu Mar 31 16:04:31 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admininfo.password
     *
     * @return the value of admininfo.password
     *
     * @mbggenerated Thu Mar 31 16:04:31 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admininfo.password
     *
     * @param password the value for admininfo.password
     *
     * @mbggenerated Thu Mar 31 16:04:31 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }
}