package entity;

public class Route {
	
	


	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.id
     *
     * @mbggenerated Tue Apr 05 23:24:41 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.name
     *
     * @mbggenerated Tue Apr 05 23:24:41 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.intro
     *
     * @mbggenerated Tue Apr 05 23:24:41 CST 2016
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.id
     *
     * @return the value of route.id
     *
     * @mbggenerated Tue Apr 05 23:24:41 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.id
     *
     * @param id the value for route.id
     *
     * @mbggenerated Tue Apr 05 23:24:41 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.name
     *
     * @return the value of route.name
     *
     * @mbggenerated Tue Apr 05 23:24:41 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.name
     *
     * @param name the value for route.name
     *
     * @mbggenerated Tue Apr 05 23:24:41 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.intro
     *
     * @return the value of route.intro
     *
     * @mbggenerated Tue Apr 05 23:24:41 CST 2016
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.intro
     *
     * @param intro the value for route.intro
     *
     * @mbggenerated Tue Apr 05 23:24:41 CST 2016
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

	public Route(String name, String intro) {
		super();
		this.name = name;
		this.intro = intro;
	}

	public Route(Integer id, String name, String intro) {
		super();
		this.id = id;
		this.name = name;
		this.intro = intro;
	}
	public Route(Long id, String name, String intro) {
		super();
		this.id = id.intValue();
		this.name = name;
		this.intro = intro;
	}
    
}