package entity;

public class RouteFavorite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_favorite.id
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_favorite.route_id
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    private Integer routeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_favorite.user_id
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_favorite.id
     *
     * @return the value of route_favorite.id
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_favorite.id
     *
     * @param id the value for route_favorite.id
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_favorite.route_id
     *
     * @return the value of route_favorite.route_id
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_favorite.route_id
     *
     * @param routeId the value for route_favorite.route_id
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_favorite.user_id
     *
     * @return the value of route_favorite.user_id
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_favorite.user_id
     *
     * @param userId the value for route_favorite.user_id
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}