package entity;

import entity.RouteFavorite;
import entity.RouteFavoriteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RouteFavoriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_favorite
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    int countByExample(RouteFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_favorite
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    int deleteByExample(RouteFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_favorite
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_favorite
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    int insert(RouteFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_favorite
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    int insertSelective(RouteFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_favorite
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    List<RouteFavorite> selectByExample(RouteFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_favorite
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    RouteFavorite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_favorite
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") RouteFavorite record, @Param("example") RouteFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_favorite
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    int updateByExample(@Param("record") RouteFavorite record, @Param("example") RouteFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_favorite
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    int updateByPrimaryKeySelective(RouteFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_favorite
     *
     * @mbggenerated Sun Apr 24 21:54:07 CST 2016
     */
    int updateByPrimaryKey(RouteFavorite record);
}