package entity;

public class RouteRating {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_rating.id
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_rating.score
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    private Float score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_rating.route_id
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    private Integer routeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_rating.user_id
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_rating.comment
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_rating.id
     *
     * @return the value of route_rating.id
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_rating.id
     *
     * @param id the value for route_rating.id
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_rating.score
     *
     * @return the value of route_rating.score
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_rating.score
     *
     * @param score the value for route_rating.score
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_rating.route_id
     *
     * @return the value of route_rating.route_id
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_rating.route_id
     *
     * @param routeId the value for route_rating.route_id
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_rating.user_id
     *
     * @return the value of route_rating.user_id
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_rating.user_id
     *
     * @param userId the value for route_rating.user_id
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_rating.comment
     *
     * @return the value of route_rating.comment
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_rating.comment
     *
     * @param comment the value for route_rating.comment
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}