package entity;

import entity.RouteRating;
import entity.RouteRatingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RouteRatingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_rating
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    int countByExample(RouteRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_rating
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    int deleteByExample(RouteRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_rating
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_rating
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    int insert(RouteRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_rating
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    int insertSelective(RouteRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_rating
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    List<RouteRating> selectByExampleWithBLOBs(RouteRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_rating
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    List<RouteRating> selectByExample(RouteRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_rating
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    RouteRating selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_rating
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") RouteRating record, @Param("example") RouteRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_rating
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") RouteRating record, @Param("example") RouteRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_rating
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    int updateByExample(@Param("record") RouteRating record, @Param("example") RouteRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_rating
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    int updateByPrimaryKeySelective(RouteRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_rating
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(RouteRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_rating
     *
     * @mbggenerated Sun Apr 24 22:27:05 CST 2016
     */
    int updateByPrimaryKey(RouteRating record);
}