package entity;

import entity.Spot;
import entity.SpotExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    int countByExample(SpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    int deleteByExample(SpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    int insert(Spot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    int insertSelective(Spot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    List<Spot> selectByExampleWithBLOBs(SpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    List<Spot> selectByExample(SpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    Spot selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") Spot record, @Param("example") SpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") Spot record, @Param("example") SpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    int updateByExample(@Param("record") Spot record, @Param("example") SpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    int updateByPrimaryKeySelective(Spot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(Spot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    int updateByPrimaryKey(Spot record);
}