package entity;

public class SpotRating {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_rating.id
     *
     * @mbggenerated Sun Apr 24 02:37:40 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_rating.score
     *
     * @mbggenerated Sun Apr 24 02:37:40 CST 2016
     */
    private Float score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_rating.spot_id
     *
     * @mbggenerated Sun Apr 24 02:37:40 CST 2016
     */
    private Integer spotId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_rating.user_id
     *
     * @mbggenerated Sun Apr 24 02:37:40 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_rating.comment
     *
     * @mbggenerated Sun Apr 24 02:37:40 CST 2016
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_rating.id
     *
     * @return the value of spot_rating.id
     *
     * @mbggenerated Sun Apr 24 02:37:40 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_rating.id
     *
     * @param id the value for spot_rating.id
     *
     * @mbggenerated Sun Apr 24 02:37:40 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_rating.score
     *
     * @return the value of spot_rating.score
     *
     * @mbggenerated Sun Apr 24 02:37:40 CST 2016
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_rating.score
     *
     * @param score the value for spot_rating.score
     *
     * @mbggenerated Sun Apr 24 02:37:40 CST 2016
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_rating.spot_id
     *
     * @return the value of spot_rating.spot_id
     *
     * @mbggenerated Sun Apr 24 02:37:40 CST 2016
     */
    public Integer getSpotId() {
        return spotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_rating.spot_id
     *
     * @param spotId the value for spot_rating.spot_id
     *
     * @mbggenerated Sun Apr 24 02:37:40 CST 2016
     */
    public void setSpotId(Integer spotId) {
        this.spotId = spotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_rating.user_id
     *
     * @return the value of spot_rating.user_id
     *
     * @mbggenerated Sun Apr 24 02:37:40 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_rating.user_id
     *
     * @param userId the value for spot_rating.user_id
     *
     * @mbggenerated Sun Apr 24 02:37:40 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_rating.comment
     *
     * @return the value of spot_rating.comment
     *
     * @mbggenerated Sun Apr 24 02:37:40 CST 2016
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_rating.comment
     *
     * @param comment the value for spot_rating.comment
     *
     * @mbggenerated Sun Apr 24 02:37:40 CST 2016
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}