package entity;

public class Spot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.id
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.name
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.pic
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.trans
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    private String trans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.intro
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.id
     *
     * @return the value of spot.id
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.id
     *
     * @param id the value for spot.id
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.name
     *
     * @return the value of spot.name
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.name
     *
     * @param name the value for spot.name
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.pic
     *
     * @return the value of spot.pic
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.pic
     *
     * @param pic the value for spot.pic
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.trans
     *
     * @return the value of spot.trans
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    public String getTrans() {
        return trans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.trans
     *
     * @param trans the value for spot.trans
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    public void setTrans(String trans) {
        this.trans = trans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.intro
     *
     * @return the value of spot.intro
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.intro
     *
     * @param intro the value for spot.intro
     *
     * @mbggenerated Fri Apr 01 09:17:31 CST 2016
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

	public Spot() {
		super();
	}

	public Spot(String name, String pic, String trans, String intro) {
		super();
		this.name = name;
		this.pic = pic;
		this.trans = trans;
		this.intro = intro;
	}

	public Spot(Integer id, String name, String pic, String trans, String intro) {
		super();
		this.id = id;
		this.name = name;
		this.pic = pic;
		this.trans = trans;
		this.intro = intro;
	}
	
    
}