package entity;

import entity.SpotRoute;
import entity.SpotRouteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpotRouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_route
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    int countByExample(SpotRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_route
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    int deleteByExample(SpotRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_route
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_route
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    int insert(SpotRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_route
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    int insertSelective(SpotRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_route
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    List<SpotRoute> selectByExample(SpotRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_route
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    SpotRoute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_route
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") SpotRoute record, @Param("example") SpotRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_route
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    int updateByExample(@Param("record") SpotRoute record, @Param("example") SpotRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_route
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    int updateByPrimaryKeySelective(SpotRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_route
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    int updateByPrimaryKey(SpotRoute record);
}