package entity;

public class SpotFavorite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_favorite.id
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_favorite.spot_id
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    private Integer spotId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_favorite.user_id
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_favorite.id
     *
     * @return the value of spot_favorite.id
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_favorite.id
     *
     * @param id the value for spot_favorite.id
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_favorite.spot_id
     *
     * @return the value of spot_favorite.spot_id
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    public Integer getSpotId() {
        return spotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_favorite.spot_id
     *
     * @param spotId the value for spot_favorite.spot_id
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    public void setSpotId(Integer spotId) {
        this.spotId = spotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_favorite.user_id
     *
     * @return the value of spot_favorite.user_id
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_favorite.user_id
     *
     * @param userId the value for spot_favorite.user_id
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}