package entity;

public class SpotRoute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_route.id
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_route.spot_id
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    private Integer spotId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_route.route_id
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    private Integer routeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_route.id
     *
     * @return the value of spot_route.id
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_route.id
     *
     * @param id the value for spot_route.id
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_route.spot_id
     *
     * @return the value of spot_route.spot_id
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    public Integer getSpotId() {
        return spotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_route.spot_id
     *
     * @param spotId the value for spot_route.spot_id
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    public void setSpotId(Integer spotId) {
        this.spotId = spotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_route.route_id
     *
     * @return the value of spot_route.route_id
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_route.route_id
     *
     * @param routeId the value for spot_route.route_id
     *
     * @mbggenerated Sat May 21 10:51:06 CST 2016
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }
}