package entity;

import entity.SpotFavorite;
import entity.SpotFavoriteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpotFavoriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_favorite
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    int countByExample(SpotFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_favorite
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    int deleteByExample(SpotFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_favorite
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_favorite
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    int insert(SpotFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_favorite
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    int insertSelective(SpotFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_favorite
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    List<SpotFavorite> selectByExample(SpotFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_favorite
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    SpotFavorite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_favorite
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    int updateByExampleSelective(@Param("record") SpotFavorite record, @Param("example") SpotFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_favorite
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    int updateByExample(@Param("record") SpotFavorite record, @Param("example") SpotFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_favorite
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    int updateByPrimaryKeySelective(SpotFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_favorite
     *
     * @mbggenerated Fri Apr 22 21:22:37 CST 2016
     */
    int updateByPrimaryKey(SpotFavorite record);
}