package entity;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbggenerated Sun Apr 24 03:04:39 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.name
     *
     * @mbggenerated Sun Apr 24 03:04:39 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.password
     *
     * @mbggenerated Sun Apr 24 03:04:39 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.status
     *
     * @mbggenerated Sun Apr 24 03:04:39 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbggenerated Sun Apr 24 03:04:39 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbggenerated Sun Apr 24 03:04:39 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.name
     *
     * @return the value of userinfo.name
     *
     * @mbggenerated Sun Apr 24 03:04:39 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.name
     *
     * @param name the value for userinfo.name
     *
     * @mbggenerated Sun Apr 24 03:04:39 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.password
     *
     * @return the value of userinfo.password
     *
     * @mbggenerated Sun Apr 24 03:04:39 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.password
     *
     * @param password the value for userinfo.password
     *
     * @mbggenerated Sun Apr 24 03:04:39 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.status
     *
     * @return the value of userinfo.status
     *
     * @mbggenerated Sun Apr 24 03:04:39 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.status
     *
     * @param status the value for userinfo.status
     *
     * @mbggenerated Sun Apr 24 03:04:39 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
    
    public Userinfo(String name, String password) {
		super();
		this.name = name;
		this.password = password;
	}

	public Userinfo(Long id, String name, String password) {
		super();
		this.id = id.intValue();
		this.name = name;
		this.password = password;
	}

	public Userinfo(Long id, String name, String password, Integer status) {
		super();
		this.id = id.intValue();
		this.name = name;
		this.password = password;
		this.status = status;
	}
	
	///java.lang.Long, java.lang.String, java.lang.String, java.lang.Integer
	
}